# API Contract Template (OpenAPI 3.0)
# Copy this for each API endpoint or service contract

openapi: 3.0.0
info:
  title: [API Name, e.g., "Article API"]
  description: [Brief description of what this API does]
  version: 1.0.0
  contact:
    name: [Team name]

servers:
  - url: https://api.example.com/v1
    description: Production
  - url: https://api-staging.example.com/v1
    description: Staging
  - url: http://localhost:3000/v1
    description: Local development

paths:
  /resource:
    get:
      summary: [Brief description, e.g., "List all articles"]
      description: |
        [Detailed description of what this endpoint does]

      operationId: listResources

      tags:
        - [Tag, e.g., "Articles"]

      security:
        - bearerAuth: []  # If authentication required

      parameters:
        - name: page
          in: query
          description: Page number for pagination
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1

        - name: limit
          in: query
          description: Number of items per page
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20

      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Resource'
                  pagination:
                    $ref: '#/components/schemas/Pagination'
              example:
                data:
                  - id: "123"
                    title: "Example"
                    createdAt: "2025-01-15T10:00:00Z"
                pagination:
                  page: 1
                  perPage: 20
                  total: 100

        '401':
          $ref: '#/components/responses/Unauthorized'

        '500':
          $ref: '#/components/responses/InternalError'

    post:
      summary: [Brief description, e.g., "Create new article"]
      description: |
        [Detailed description]

      operationId: createResource

      tags:
        - [Tag]

      security:
        - bearerAuth: []

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateResourceRequest'
            example:
              title: "New Article"
              content: "Article content here"

      responses:
        '201':
          description: Resource created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Resource'
              example:
                data:
                  id: "124"
                  title: "New Article"
                  createdAt: "2025-01-15T10:05:00Z"

        '400':
          $ref: '#/components/responses/BadRequest'

        '401':
          $ref: '#/components/responses/Unauthorized'

        '422':
          $ref: '#/components/responses/ValidationError'

        '500':
          $ref: '#/components/responses/InternalError'

  /resource/{id}:
    get:
      summary: [Brief description, e.g., "Get article by ID"]
      operationId: getResourceById
      tags:
        - [Tag]
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: Resource ID
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Resource'
        '404':
          $ref: '#/components/responses/NotFound'
        '401':
          $ref: '#/components/responses/Unauthorized'

    put:
      summary: [Brief description, e.g., "Update article"]
      operationId: updateResource
      tags:
        - [Tag]
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateResourceRequest'
      responses:
        '200':
          description: Resource updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Resource'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/ValidationError'

    delete:
      summary: [Brief description, e.g., "Delete article"]
      operationId: deleteResource
      tags:
        - [Tag]
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Resource deleted successfully
        '404':
          $ref: '#/components/responses/NotFound'
        '401':
          $ref: '#/components/responses/Unauthorized'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token obtained from /auth/login

  schemas:
    Resource:
      type: object
      required:
        - id
        - title
        - createdAt
      properties:
        id:
          type: string
          format: uuid
          description: Unique resource identifier
        title:
          type: string
          minLength: 1
          maxLength: 200
          description: Resource title
        content:
          type: string
          description: Resource content
        status:
          type: string
          enum: [draft, published, archived]
          description: Resource status
        createdAt:
          type: string
          format: date-time
          description: Creation timestamp
        updatedAt:
          type: string
          format: date-time
          description: Last update timestamp

    CreateResourceRequest:
      type: object
      required:
        - title
        - content
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 200
        content:
          type: string
          minLength: 1

    UpdateResourceRequest:
      type: object
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 200
        content:
          type: string
        status:
          type: string
          enum: [draft, published, archived]

    Pagination:
      type: object
      properties:
        page:
          type: integer
          minimum: 1
        perPage:
          type: integer
          minimum: 1
          maximum: 100
        total:
          type: integer
          minimum: 0
        totalPages:
          type: integer
          minimum: 0

    Error:
      type: object
      required:
        - status
        - message
      properties:
        status:
          type: string
          enum: [error]
        message:
          type: string
          description: Human-readable error message
        code:
          type: string
          description: Machine-readable error code
        details:
          type: object
          description: Additional error details

    ValidationError:
      type: object
      required:
        - status
        - message
        - errors
      properties:
        status:
          type: string
          enum: [error]
        message:
          type: string
        errors:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
              message:
                type: string

  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            status: error
            message: "Invalid request parameters"
            code: "BAD_REQUEST"

    Unauthorized:
      description: Unauthorized - missing or invalid authentication
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            status: error
            message: "Authentication required"
            code: "UNAUTHORIZED"

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            status: error
            message: "Resource not found"
            code: "NOT_FOUND"

    ValidationError:
      description: Validation error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ValidationError'
          example:
            status: error
            message: "Validation failed"
            errors:
              - field: "title"
                message: "Title is required"
              - field: "content"
                message: "Content must be at least 1 character"

    InternalError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            status: error
            message: "Internal server error"
            code: "INTERNAL_ERROR"
